/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : KBI1.h
**     Project     : cartesd_temperature_gsm_ok01
**     Processor   : MK64FN1M0VLQ12
**     Component   : GenericKBI
**     Version     : Component 01.025, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-23, 11:03, # CodeGen: 6
**     Abstract    :
**
**     Settings    :
**          Component name                                 : KBI1
**          Single Key                                     : Enabled
**            KBI interface                                : kbi
**          Multiple Keys                                  : Disabled
**     Contents    :
**         Enable  - void KBI1_Enable(void);
**         Disable - void KBI1_Disable(void);
**         GetVal  - byte KBI1_GetVal(void);
**
**     (c) Copyright Erich Styger, 2009
**     http      : www.hslu.ch
**     mail      : erich.styger@hslu.ch
** ###################################################################*/
/*!
** @file KBI1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup KBI1_module KBI1 module documentation
**  @{
*/         

#ifndef __KBI1_H
#define __KBI1_H

/* MODULE KBI1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "KeyISRpin1.h"

#include "Cpu.h"




void KBI1_Enable(void);
/*
** ===================================================================
**     Method      :  KBI1_Enable (component GenericKBI)
**     Description :
**         Enables generation of the interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void KBI1_Disable(void);
/*
** ===================================================================
**     Method      :  KBI1_Disable (component GenericKBI)
**     Description :
**         Disable the generation of interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

byte KBI1_GetVal(void);
/*
** ===================================================================
**     Method      :  KBI1_GetVal (component GenericKBI)
**     Description :
**         Returns the value of the interrupt pin
**     Parameters  : None
**     Returns     :
**         ---             - state of the pin(s)
** ===================================================================
*/

void KeyISRpin1_OnInterrupt(void);

/* END KBI1. */

#endif
/* ifndef __KBI1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
