/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : KBI1.c
**     Project     : cartesd_temperature_gsm_ok01
**     Processor   : MK64FN1M0VLQ12
**     Component   : GenericKBI
**     Version     : Component 01.025, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-30, 09:06, # CodeGen: 10
**     Abstract    :
**
**     Settings    :
**          Component name                                 : KBI1
**          Single Key                                     : Enabled
**            KBI interface                                : kbi
**          Multiple Keys                                  : Disabled
**     Contents    :
**         Enable  - void KBI1_Enable(void);
**         Disable - void KBI1_Disable(void);
**         GetVal  - byte KBI1_GetVal(void);
**
**     (c) Copyright Erich Styger, 2009
**     http      : www.hslu.ch
**     mail      : erich.styger@hslu.ch
** ###################################################################*/
/*!
** @file KBI1.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup KBI1_module KBI1 module documentation
**  @{
*/         

/* MODULE KBI1. */

#include "Events.h"
#include "KBI1.h"

/*
** ===================================================================
**     Method      :  KBI1_Enable (component GenericKBI)
**     Description :
**         Enables generation of the interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBI1_Enable(void)
{
  KeyISRpin1_Enable();
}

/*
** ===================================================================
**     Method      :  KBI1_Disable (component GenericKBI)
**     Description :
**         Disable the generation of interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBI1_Disable(void)
{
  KeyISRpin1_Disable();
}

/*
** ===================================================================
**     Method      :  KBI1_GetVal (component GenericKBI)
**     Description :
**         Returns the value of the interrupt pin
**     Parameters  : None
**     Returns     :
**         ---             - state of the pin(s)
** ===================================================================
*/
byte KBI1_GetVal(void)
{
  return (byte)((KeyISRpin1_GetVal()!=0));
}

/*
** ===================================================================
**     Method      :  KBI1_OnInterrupt (component GenericKBI)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void KeyISRpin1_OnInterrupt(void)
{
  KBI1_OnInterrupt();
}

/* END KBI1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
